### ISSUE TITLE
Overovaci otazka ve foru neni videt

### ISSUE THREAD

**Issue by mahdi1234** [lemmingucwcz/DarkRoot#5]
Ve foru pro neprihlaseneho uzivatele je po aplikaci stylu 1.1 neviditelna sekce s overenim, tudiz nelze odeslat prispevek.

**Comment by lemmingucwcz** [comment]
Jasně, protože ten styl je dělaný na root.cz a ne na forum.root.cz.

Na forum.root.cz jsi ho aplikoval ty ručně, nebo to udělal nějaký plugin?

**Comment by mahdi1234** [comment]
Ano pres rozsireni Stylish - https://addons.mozilla.org/en-US/seamonkey/addon/stylish/

Nicmene uz vim proc, staci zmenit na a pak uz se neaplikuje na subdomeny,
`@-moz-document domain(www.root.cz) {`

**Comment by lemmingucwcz** [comment]
Díky, upravena definice na userstyles.org
